{{/*
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.file.name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.file.targetSecretName }}
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.file.awsSecretName }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
*/}}
