replicaCount: 1

image:
  repository: jmutai/kuard-amd64
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80

httproute:
  enabled: true
  gateway:
    name: main-gateway
    namespace: default
  host: app1.chetan.local
  path: /
  pathType: PathPrefix

configEnv:
  APP_NAME: App 1
  ENVIRONMENT: Development
  FEATURE_ENABLED: "true"

configFile:
  hello.sh: |
    #!/bin/sh
    echo "Hello from the ConfigMap script!"
    echo "Current time: $(date)"

# externalSecrets:
#   awsRegion: ap-south-1
#   credentialsSecretName: aws-secretsmanager-credentials
#   env:
#     name: app1-external-secret-env
#     targetSecretName: app1-secret-env
#     awsSecretName: argocd-demo/app-secrets
#   file:
#     name: app1-external-secret-file
#     targetSecretName: app1-secret-file
#     awsSecretName: argocd-demo/app-secret-file

volumes:
  scriptsMountPath: /scripts
  # awsSecretFileMountPath: /aws-secrets
  defaultMode: 0755

resources:
  requests:
    memory: 64Mi
    cpu: 256m
  limits:
    memory: 128Mi
    cpu: 512m
