{{- if .Values.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config-file
data:
  {{- range $key, $value := .Values.configFile }}
  {{ $key }}: |
{{ $value | indent 4 }}
  {{- end }}
{{- end }}
