apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

helmGlobals:
  chartHome: ../../../apps

helmCharts:
  - name: app1
    releaseName: app1
    valuesFile: values.yaml
    namespace: dev

labels:
  - includeSelectors: false
    pairs:
      app: app1
      environment: development
      branch: dev
